# Generated by Django 3.1.4 on 2020-12-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('credentialId', models.CharField(max_length=300)),
                ('pubKey', models.CharField(max_length=500)),
                ('signCount', models.IntegerField(default=0)),
            ],
        ),
    ]
