# Generated by Django 3.1.4 on 2021-01-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauthn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='alg',
            field=models.IntegerField(default=0),
        ),
    ]
