# Generated by Django 3.1.4 on 2020-12-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauthn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
