# Generated by Django 3.0.4 on 2021-01-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauthn', '0002_key_transports'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='aaguid',
            field=models.CharField(default='', max_length=32),
        ),
    ]
