# Generated by Django 3.0.4 on 2021-01-16 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webauthn', '0003_key_aaguid'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('uid', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='session',
            name='username',
        ),
        migrations.AddField(
            model_name='key',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webauthn.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webauthn.User'),
        ),
    ]
