# Generated by Django 3.0.4 on 2021-01-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webauthn', '0004_auto_20210116_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='key',
            name='username',
        ),
    ]
