# Generated by Django 3.0.4 on 2021-01-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauthn', '0006_auto_20210117_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='fmt',
            field=models.CharField(default='', max_length=30),
        ),
    ]
