# Generated by Django 3.0.4 on 2021-01-30 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webauthn', '0007_key_fmt'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteSession',
            fields=[
                ('session_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webauthn.Session')),
                ('verified', models.BooleanField(default=False)),
            ],
            bases=('webauthn.session',),
        ),
    ]
