# Generated by Django 3.1.4 on 2021-06-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webauthn', '0008_remotesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='key',
            old_name='credentialId',
            new_name='credential_id',
        ),
        migrations.RenameField(
            model_name='key',
            old_name='credentialPublicKey',
            new_name='credential_public_key',
        ),
        migrations.RenameField(
            model_name='key',
            old_name='signCount',
            new_name='sign_count',
        ),
    ]
